---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:8
    pre_build_image: true
    
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    
  - name: oraclelinux
    image:    docker.io/library/oraclelinux:8 
    pre_build_image: true

provisioner:
  name: ansible
verifier:
  name: ansible

# ---
# driver:
#   name: docker
# platforms:
#   - name: instance
#     image: quay.io/centos/centos:stream8
#     pre_build_image: true
